apiVersion: v1
kind: Service
metadata:
  name: {{ include "airflow.fullname" . }}-web
  {{- if .Values.web.service.annotations }}
  annotations:
    {{- toYaml .Values.web.service.annotations | nindent 4 }}
  {{- end }}
  labels:
    app: {{ include "airflow.labels.app" . }}
    component: web
    chart: {{ include "airflow.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ include "airflow.labels.app" . }}
    component: web
    release: {{ .Release.Name }}
  sessionAffinity: {{ .Values.web.service.sessionAffinity }}
  {{- if .Values.web.service.sessionAffinityConfig }}
  sessionAffinityConfig:
    {{- toYaml .Values.web.service.sessionAffinityConfig | nindent 4 }}
  {{- end }}
  type: NodePort
  ports:
    - name: web
      appProtocol: {{ include "airflow.web.appProtocol" . | quote }}
      protocol: TCP
      port: {{ .Values.web.service.externalPort | default 8080 }}
      nodePort: 32080
      targetPort: 8080
